name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Permitir ejecución manual desde la pestaña Actions
  workflow_dispatch:

# Configurar permisos para que el token de GITHUB_TOKEN pueda desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evitar despliegues simultáneos redundantes
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  BUILD_PATH: '.'

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Setup GitHub Pages Environment
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build Astro Static Site
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    name: Deploy to Live Site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
